### ISSUE TITLE
Adopt JSCS or migrate to ESLint

### ISSUE THREAD

**Issue by redoPop** [tedconf/code-style-guides#17]
JSHint has demarcated "code correctness" vs. "code style" issues, has deprecated configuration options covering code style ([`camelcase`](http://jshint.com/docs/options/#camelcase), [`newcap`](http://jshint.com/docs/options/#newcap), etc.), and recommends replacing these options with [JSCS](http://jscs.info/).

Another option is to replace JSHint with [ESLint](http://eslint.org/), which provides linting for code correctness _and_ code style issues.

We should assess the pros and cons of these tools to decide which is best suited for our needs.

**Comment by brenna** [comment]
uniformed +1 for JSCS because it has a lot of support behind it and it comes with a lot of [presets](http://jscs.info/overview#presets) from reputable sources.

How closely is ESLint tied to JSX?

**Comment by samselikoff** [comment]
https://github.com/dockyard/ember-suave is a well-maintained JSCS integration story for Ember apps. I've been meaning to throw it into our Ember apps to get the ball rolling. If we go that route, I think we could have a single JSCS file that gets enforced in all our JS (Ember and non-Ember).

**Comment by ryanto** [comment]
:+1:

**Comment by heygrady** [comment]
I've been hearing more about ESLint from my friends in the industry. A close friend working in React for Yahoo was recently pushing me to try ESLint. I have no personal experience.

**Comment by redoPop** [comment]
ESLint was [updated to include JSX support](http://eslint.org/blog/2014/11/es6-jsx-support/) which probably explains why React developers are especially keen on it.

It sounds as though JSHint is preferred by the Ember community, in which case I'd be inclined toward the JSHint+JSCS route, especially given JSCS's preference for style guide presets which Sam mentioned.

I stumbled across a couple of comparisons online:

* [The Google web-starter-kit team settled on ESLint](https://github.com/google/web-starter-kit/issues/747)
* [Jani Hartikainen (Microsoft) prefers ESLint](http://www.sitepoint.com/comparison-javascript-linting-tools/)

In both cases it feels as though the developers are comparing ESLint to JSHint or JSCS in isolation, so I'm not sure their insights have much applicability for us.

Comparing [JSCS rules](http://jscs.info/rules) vs [ESLint's style rules](http://eslint.org/docs/rules/#stylistic-issues) suggests that JSCS provides significantly more fine-grained control for stylistic issues.

Many of ESLint's other rules are inherited from [JSHint's rules](http://jshint.com/docs/options/), but it does add [several rules covering ES6 specifically](http://eslint.org/docs/rules/#ecmascript-6).

[ESLint admits to being slower than JSHint in isolation](https://www.npmjs.com/package/eslint#how-does-eslint-performance-compare-to-jshint-and-jscs). I don't know that this would be true of JSHint and JSCS running together, but the [SublimeLinter-eslint](https://github.com/roadhump/SublimeLinter-eslint) ST module has caused me some performance issues while testing things out on my MacBook Air.

Another factor to bear in mind is that we already have JSHint rules in most of our repos, and although migration tools do exist the move to JSHint+JSCS would still be simpler and cleaner.

**Comment by brenna** [comment]
Thanks for all the research, @redoPop! What you've presented is enough for me to feel confident in moving forward with JSCS. I'd rather get up and running with this quickly than debate much further.

**Comment by redoPop** [comment]
Thanks for the input, all!

JSCS seems to suit our needs a bit better for now. We can reassess this in future e.g. if ES6/JSX become key considerations for us before the JSHint+JSCS teams are able to address them.

But today: JSCS!
