### ISSUE TITLE
kick off JS style guide

### ISSUE THREAD

**Issue by brenna** [tedconf/code-style-guides#25]
Let's get started with a fork or link to an existing JS style guide. Name your favourites and we can pick one to use as our starting point. 

Here are some on my radar:
https://github.com/Khan/style-guides/blob/master/style/javascript.md
https://github.com/airbnb/javascript *
https://github.com/rwaldron/idiomatic.js#idiomatic-style-manifesto *

*available as JSCS preset, choosing one of the presets might be advantageous for easy enforcement

cc/ @redoPop @ryanto @samselikoff

**Comment by samselikoff** [comment]
I'm generally a fan of airbnb's guide, happy to start with a fork + modify as issues arise.

Thanks for kicking this off!

**Comment by redoPop** [comment]
Tough call! Khan's guide is wonderfully lucid, Airbnb's guide is wonderfully indexed, and idiomatic.js is wonderfully sassy.

That Airbnb's rules are so thorough, so well indexed, and [are already available as a JSCS preset](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json) makes it particularly tempting to me. There are a few places where I disagree with it [like `eqeqeq`](https://github.com/airbnb/javascript#comparison-operators--equality), [or `prefer-const`](https://github.com/airbnb/javascript#2.1), but it's much easier to have those conversations when you have something this thorough to base them on.

idiomatic.js is the only one to mention [Editorconfig](http://editorconfig.org/), though.

**Comment by samselikoff** [comment]
Editorconfig is great, Ember apps come with a `.editorconfig` file. Those config options are independent of these and/or JSCS presets, right?

If so, I say let's start with airbnb's and go from there?

**Comment by redoPop** [comment]
There's potential [here](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json#L77) ([18.1](https://github.com/airbnb/javascript#18.1)) for conflict between `.editorconfig` and Airbnb JSCS presets, but in practice I don't think I've seen any of us use anything other than two-space indentation in our JS. as long as our `.editorconfig` rules and JSCS rules are in agreement it shouldn't be an issue.

**Comment by redoPop** [comment]
(+1 for starting with Airbnb and forking wherever we have shared disagreements with Airbnb styles.)

**Comment by brenna** [comment]
Agree that an airbnb fork is a good starting point. We can revise what we
don't like and add what we like from the others!

**Comment by redoPop** [comment]
I created an Airbnb fork in 8d78c3e0d9e749e488370867a7a7575da7e6a347.

I think I'd like to keep linter configurations to this repository too. I've opened #28 to discuss further.

I think that means we can close this one and open new issues for individual changes we want to make to Airbnb's guide. Any opposed?

**Comment by samselikoff** [comment]
Sounds great, go for it!

**Comment by hzoo** [comment]
Let us know if you guys need help with anything for JSCS - I see @redoPop already has a PR open so thanks for that.

**Comment by redoPop** [comment]
Thanks, @hzoo! :) JSCS has been working out really well for us.

Closing this issue per 8d78c3e0d9e749e488370867a7a7575da7e6a347 and #28. Thanks, all!

**Comment by VinSpee** [comment]
Break out your paint brushes and WD-40. JSCS is dead.

Starting today, most of the JSCS maintainers will join the ESLint team.
https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2%23.ydsl2xxae

**Comment by hzoo** [comment]
Well we're deprecating it, not killing it. We'll still be fixing bugs etc just no major releases from us and we are helping out switching users to ESLint eventually

**Comment by VinSpee** [comment]
@hzop kill may have been strong language. I simply meant we should switch to ESLint at our leisure. 

Thanks for the clarification!
