### ISSUE TITLE
Adding linter configurations to the code-style-guides repository

### ISSUE THREAD

**Issue by redoPop** [tedconf/code-style-guides#28]
I'd like to keep linter configurations (e.g. [`.jshintrc`](https://github.com/airbnb/javascript/blob/master/linters/.jshintrc), [`.jscsrc`](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json)) in this repository too so we can easily update them as we make changes to our code style guides and have a nice paper trail to follow if we forget the reasoning about a particular topic.

In this issue I'd like to come to a group decision about:

1. Whether it's appropriate to keep linter configurations in this repository.
2. The architecture (i.e. folder structure) we should use to organize linter configurations.

**Comment by redoPop** [comment]
A naive suggestion for number 2 above: a directory named "linters" with subdirectories named for each linter we use, each containing a configuration file for that linter:

```
linters
└── editorconfig
    └── .editorconfig
└── jscs
    └── .jscsrc
└── jshint
    └── .jshintrc
└── rubocop
    └── .rubocop.yml
```

**Comment by alexdean** [comment]
keeping human-readable style guides and the machine-oriented config files that help enforce those guides in the same repo makes a lot of sense to me.

**Comment by redoPop** [comment]
I agree! :smile: It looks like rubocop's config will become code-style-guides' first linter config in #30. I think we can use that PR as a model to answer both of these questions implicitly.

**Comment by CpuID** [comment]
An interesting question, how do we deal with the scenario of executing the machine readable configs on a per repo basis? Manually copying them into each repo?

I guess one idea once things mature a bit here, would be to modify the Jenkins scripts to pull in the central style guide file if some variable/file exists in the repo (like `touch .central_style_guides`) at test runtime.

Thoughts?

**Comment by redoPop** [comment]
> Manually copying them into each repo

For now, yep. Some linting tools offer their own centralization solutions, others don't, and none are universal.

In the meantime, we can think of these as our canonical linter configs which individual projects would consciously decide to adopt and, as necessary, update.

**Comment by CpuID** [comment]
np we can always iterate on things over time :)
