### ISSUE TITLE
Use of Sass `&` for class concatenation

### ISSUE THREAD

**Issue by redoPop** [tedconf/code-style-guides#3]
(Note: this is an archival summary of a discussion held elsewhere.)

Proposal: use the `&` operator to concatenate class name selectors together.

For example, this:

    .Block {
      padding: 10px;
    }

    .Block__element {
      margin: 10px;
    }

…would become:

    .Block {
      padding: 10px;

      &__element {
        margin: 10px;
      }
    }

## Benefits

* Renaming a block becomes as simple as renaming the parent class in the nest. This is especially useful during early development, where blocks are moved and renamed very frequently.
* The Sass is less repetitive to read and write.
* The resultant nesting is highly suggestive of the relationship between parent Blocks and their child elements.

#### Deep nesting

Hyperbole:

	.Block {
		margin: 40px 0;

		&__foo {
			padding: 20px;

			&__bar {
				background: #FFF;
				color: #000;

				&--quz {
					color: #333;
				}
			}
		}
	}

It's difficult to tell at a glance that the last leaf produces the class name `Block__foo__bar--quz` – the reader has to walk up the tree of concatenation to work this out.

It's relatively rare that we need to specify elements this deeply, but if/when we do, complete and explicit class names are more readable at a glance.

#### Confusion with combinators

Using `&` for class name concatenation looks very similar to combinator nesting:

	.thing1 {
		.finger {
			color: black;
		}
	}

	.thing2 {
		&-finger {
			color: black;
		}
	}

Unnecessary specificity via nesting is a bad habit people often slip into when they first start using Sass, which led to the creation of [the inception rule](http://thesassway.com/beginner/the-inception-rule). With the inception rule, nested blocks `{ … }` are a handy red flag for overly specific CSS. It's easy to tell at a glance that you need to re-think your code.

Using `&` for concatenation makes the inception rule harder for humans to follow because the concatenated class names look almost exactly like extra specificity (as in the examples above). What looks like bad Sass may actually be okay CSS.

Without using `&` for nested concatenation, the code's specificity level is much easier to scan:

	.thing2-finger {
		color: black;
	}

#### Relative esotericism

This is very subjective, but I consider nested use of `&` for concatenation to be a relatively advanced/esoteric feature of Sass, in part for the two reasons mentioned above: you have to pay closer than the usual attention when reading it to determine the output you'll be producing.

Not all of our Sass is always maintained by front-end devs. e.g., ted.com's CSS is often edited by server-side engineers in a hurry, and by Product people with varying levels of experience with Sass. The more CSS-like the Sass, the lower the barrier to entry for others.

#### Grep/ack/"Find in files"

Sometimes people have to do an emergency fix on an unfamiliar file layout. In those cases it's nice to be able to quickly grep a unique footprint to find the responsible Sass source. Obviously, that's not easily done if the class names are concatenated via `&` ;)

## Conclusion

Not all of the concerns listed apply to every project.

We have decided to leave the decision of whether to disallow or enforce this style as a project-specific concern for now.

**Comment by samselikoff** [comment]
I'd actually like to open this one back up for discussion.

If I'm not mistaken, currently most of our public-facing/non-Ember apps write out the full selector, and most of our Ember apps use concatenation. Lesson Creator is the first public-facing Ember app I've worked on, and I'm looking to incorporate styles from RoadRunner there. Besides that, I just don't think there's a good reason for this inconsistency across our apps.

Joe had some specific objections to concatenation above, and prefers full selectors. I have a weak preference for concatenation, but could go either way. Questions for yall:

 1. @redoPop, am I correct that you still have a strong preference for full selectors?
 1. @brenna and @ryanto, where are you all at on this?
 2. I think it's important for us to standardize on this. If we get tedconf/styles moving in earnest, and as we bounce around between projects, developers shouldn't have to encounter different coding styles. It's unnecessary cognitive load. So the question is, do you all agree that this is worth standardizing?

I will leave you all with this beautiful concatenated example of a stylesheet from lesson creator:

```sass
$gutter: 0px;
$breakpoint: 840px;

.Lesson-creator {
  max-width: 960px;
  margin: 0 auto;

  @include above($main-breakpoint) {
    min-height: calc(100vh + 113px);
    padding-top: 20px;
    padding-left: 15px;
    padding-right: 15px;
  }

  &__row {
    @include make-row($gutter);
  }
  &__left-panel {
    @include make-column(3, $breakpoint, $gutter);
  }
  &__center-panel {
    @include make-column(9, $breakpoint, $gutter);
  }
  &__section {

    &.ted-panel-open {
      margin-bottom: 30px;
    }
  }
  &__heading {
    font-weight: bold;
    color: #555;
    font-size: 18px;
    line-height: 25px;
    margin-top: 20px;
    margin-bottom: 30px;
  }

  &__inverse-module {
    margin-top: 20px;
    padding-top: 35px;
    padding-bottom: 40px;
    border-top: 4px solid #777;
    background-color: rgb(240,240,240);
  }

}
```

Isn't it purdy? :wink:

**Comment by brenna** [comment]
I prefer concatenation when used for BEM element/modifier classes, for readability, efficiency, and because it clearly indicates the BEM module structure. Also really handy for pseudo-classes, like :hover.

Search is a bit of a non-issue if you can search for the BEM block, and/or enable source maps. I hear your concern about non-FED's but we can alleviate that by surfacing BEM naming conventions and the Inception Rule in these style guide.

We could also look into CSS linting to enforce good nesting practices.

**Comment by redoPop** [comment]
Afraid I still have a fairly strong preference for full selectors. ([Sorry!](http://i.imgur.com/JfUijq6.png))

Per my comments under "Confusion with combinators" (e.g. `&.spesh { … }` vs. `&--spesh { … }`) this style makes the inception rule harder for humans to follow. It's possible Sass linters are able to compensate for that problem, which is worth investigating for its own reasons. If it turns out to be the case, we'd need to enforce linting wherever we adopt this style for it to be considered an applicable workaround.

My other concern is the mental processing required when this style is applied to deep ancestors (my comments under "Deep nesting"). A potential workaround could be to insist that the concatenation style only be used for elements and modifiers of the block itself, and never for grandchild elements or modifiers of elements.

**Comment by samselikoff** [comment]
I may be confused, but are you saying

```
.Element.spesh {
}

.Element--speesh {
}
```

is easier to distinguish than

```
.Element {

  &.spesh {
  }

}
.Element {

  &--spesh {
  }

}
```

?

Also, re: nesting, I can't remember the last time I've used grandchild (or deeper) elements or modifiers, so I can't really relate to this concern.

**Comment by redoPop** [comment]
Sort of, but think _Sassier_. ;) I'm highlighting the difference between:

```
.Element {
	&.spesh {
		…
	}
}

.Element--spesh {
	…
}
```

vs:

```
.Element {
	&.spesh {
		…
	}

	&--spesh {
		…
	}
}
```

In the second example, the concatenation looks very similar to a Sassy combinator, and makes it easier for undesirable specificity to go unnoticed.

Re-reading your earlier example more closely, I'm now noticing that you have a combinator exactly like this with `&.ted-panel-open`. I missed this the first time I skimmed your code because it looks exactly like the concatenated blocks surrounding it.

**Comment by brenna** [comment]
So, can we settle on only use the & combinator for BEM elements and
modifiers, and only go 1 level on that?

**Comment by samselikoff** [comment]
I'm inclined to say we don't have sufficient buy-in one way or the other here, meaning it's not important enough to standardize across all our projects. Especially given basically all our Ember apps use concatenation and many (most?) other apps probably don't. 

Let's leave it as resolved above, it's a per-project decision and we just know to code in the style the project's already established.

**Comment by redoPop** [comment]
I think I'd feel more comfortable with this for now, at least until we've used Sass linting in enough projects to have confidence that it will identify things like over-specificity intelligently. I've opened #27 so we can address that.
