### ISSUE TITLE
Sass vs CSS guidelines

### ISSUE THREAD

**Issue by redoPop** [tedconf/code-style-guides#34]
I just opened #33 and noticed something a little strange:

I expressed [the rule](https://github.com/tedconf/code-style-guides/pull/33#issue-142505924) in terms of pure CSS, which made sense to me at the time of writing: `css.md` is for our _CSS_ guidelines, after all! However, that means it _appears_ to conflict with the "organize styles primarily by class" rule (#22) which is Sass-specific. In fact, the two rules complement one another: Sass does the work of pulling apart the class-nested media queries we prefer and turning them back into valid CSS. It's only when CSS and Sass code are combined in the same document that the two rules appear to be in conflict.

I can imagine similar situations presenting themselves in future.

Should we set up a separate supplementary guide for Sass-specific guidelines? Should we change our "CSS guidelines" to "Sass guidelines" until we need something more?

/Cc @brenna, @samselikoff, @VinSpee, @ryanto for discussion!

**Comment by VinSpee** [comment]
If we do opt for a future-CSS syntax (which I am an advocate of), this documentation would still apply, as the [@nesting spec](http://tabatkins.github.io/specs/css-nesting/) looks and behaves the same.

**Comment by redoPop** [comment]
I can imagine `@nest` being adopted as a special class of at-rule; similar to the way [conditional group rules](https://www.w3.org/TR/css3-conditional/) were established to allow nesting of certain at-rules within one another. In that case, it may not help us much with the `@media` problem.

I could be wrong about that, but I also find this kind of ambiguity inherent in spec proposals, and it makes me very wary of using them as a basis for code style recommendations. At the very least, I'd expect recommendations in a "CSS guidelines" document to work unmodified in the majority of today's browsers.

**Comment by VinSpee** [comment]
In that case, I'd advice against a "plain CSS" guide, as it is unlikely someone would be writing plain CSS, and they could ascertain the standards from the current guide.

**Comment by redoPop** [comment]
Yep. Seconded.

Anyone opposed to the following plan of action?

1. Rename `css.md` → `sass.md`
2. Retitle it "CSS guidelines" → "Sass guidelines"
3. Relabel all "css" issues in this repo → "sass"
4. Remove the "sass" label from this repo
5. Maintain future stylesheet recommendations from a Sass-specific perspective

**Comment by redoPop** [comment]
Resolved in #35.
