### ISSUE TITLE
Rubocop or Ruby are high, one of the two (redundant else clauses)

### ISSUE THREAD

**Issue by CpuID** [tedconf/code-style-guides#37]
Current code:

```
    if map.has_key?(issuer)
      map[issuer]
    else
      nil
    end
```

Results work as expected (map[issuer] returned in the correct scenarios).

Rubocop Suggestion:

```
capistrano/recipes.d/ssl.rb:136:5: C: Redundant else-clause.
```

Tested as:

```
    if map.has_key?(issuer)
      map[issuer]
    end
    nil
```

And end up getting nil 100% of the time :( In theory though the code feels like it should work correctly, somethings off.

**Comment by CpuID** [comment]
cc @DanielRussell - causing the infrastructure repo jenkins runs to fail currently.

**Comment by alexdean** [comment]
```ruby
if map.has_key?(issuer)
  map[issuer]
end
nil
```

this will always return `nil`. maybe you want

```ruby
if map.has_key?(issuer)
  return map[issuer]
end
nil
```

**Comment by alexdean** [comment]
or

```ruby
return map[issuer] if map.has_key?(issuer)
```

**Comment by CpuID** [comment]
I agree with the syntax of:

```
if map.has_key?(issuer)
  return map[issuer]
end
nil
```

Yet rubocop doesn't :)

I'll have a play a bit more, I see @DanielRussell also disabled Style/EmptyElse on our repo, all good.

**Comment by alexdean** [comment]
i think there are multiple unrelated failures here, and disabling `Style/EmptyElse` won't resolve things. Using the `--display-cop-names` flag is really useful here, to see which problem you're actually having.

## option 1

```ruby
# test.rb
if map.has_key?(issuer)
  return map[issuer]
end
nil
```

```
$ rubocop test.rb --display-cop-names
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if map.has_key?(issuer)
^^
test.rb:1:8: C: Style/DeprecatedHashMethods: Hash#has_key? is deprecated in favor of Hash#key?.
if map.has_key?(issuer)
       ^^^^^^^^

1 file inspected, 2 offenses detected
```

There are 2 failures, but not `Style/EmptyElse`. 

## option 2

```ruby
# test.rb
return map[issuer] if map.has_key?(issuer)
```

```
$ rubocop test.rb --display-cop-names
Inspecting 1 file
C

Offenses:

test.rb:1:27: C: Style/DeprecatedHashMethods: Hash#has_key? is deprecated in favor of Hash#key?.
return map[issuer] if map.has_key?(issuer)
                          ^^^^^^^^

1 file inspected, 1 offense detected
```

## option 3

```ruby
# test.rb
return map[issuer] if map.key?(issuer)
```

```
$ rubocop test.rb --display-cop-names
Inspecting 1 file
.

1 file inspected, no offenses detected
```

# Don't forget!

static analysis != tests. rubocop is a style checker not a testing tool. changing code to make rubocop pass can change behavior and break things. (For instance, i'm not positive if `#has_key?` and `#key?` are truly identical. You'd need to verify that before making these changes.)

**Comment by alexdean** [comment]
@CpuID can i close this one?

**Comment by CpuID** [comment]
Yea why not, nothing to action immediately. I can come back to it if I need a reference in future.

**Comment by mrothenbuhler** [comment]
Ternary operator fixed this for me. Didn't know ruby had it

value_i_want = map.has_key?(issuer) ? map[issuer] : nil
