### ISSUE TITLE
Use qualified selectors instead of block prefixes for BEM modifiers

### ISSUE THREAD

**Issue by redoPop** [tedconf/code-style-guides#4]
(Note: issue description summarizes a discussion that began elsewhere.)

Currently, our modifier class names are prefixed with the block (and potentially element) context, separated by `--` (two hyphens):

	.Block--modifier { … }
	<div class="Block Block--modifier">

Instead, we could use qualified selectors and skip this prefix:

	.Block.is--modifier { … }
	<div class="Block is--modifier">

1. Modifier class names written this way would never be styled independently of their block context (e.g. `.is--modifier { color: #F00 }`). They would only be styled using qualified selectors that pair them with a block (e.g. `.Block.is--modifier { color: #F00 }`).
2. A prefix is used to distinguish modifier classes from general utility classes and third party CSS. I've used `is--` as a prefix in this example. Any prefix could potentially be used, as long as it's consistent.

## Advantages

* Reduced repetition in HTML and JavaScript. e.g. `addClass('is--active')` vs. `addClass('Block--active')`
* Opportunities for automated tools to consolidate CSS for identically named modifiers that share common styles.

#### Increased specificity

This style increases specificity in a way that can lead to surprising results:

	<style>
		.Foo { font-size:80px; }
		.Foo.is--baz { background: red; }

		.Bar { background: green; }
	</stlye>

	<div class="Foo is--baz Bar">&#9731;</div>

From the order of the CSS, you might expect the `div`'s background to be green per `.Bar`, but the qualified selector is more specific, causing its background to be red.

This seems like it could lead to the kind of specificity wars BEM was devised to help avoid.

#### Ambiguous composability

BEM blocks are sometimes interwoven when applied to elements. Consider the following:

	<div class="Foo">
		<div class="Foo__bar is--baz Qux">

Does `is--baz` modify `Foo__bar`, or does it modify `Qux`? It's impossible to tell from the HTML alone.

#### Naming conflicts

Consider this HTML:

	<div class="Foo is--baz Bar">

`Foo` and `Bar` may each have their own `is--baz` modifier defined for different purposes.

Adding `is--baz` to this HTML would trigger both modifiers, which may not be intended or desirable.

**Comment by redoPop** [comment]
In this case I think the utility of the proposal is outweighed by the concerns it raises.

**Comment by samselikoff** [comment]
I agree, we can close this
