### ISSUE TITLE
Create editorconfig configuration

### ISSUE THREAD

**Issue by DanielRussell** [tedconf/code-style-guides#56]
Create an [editorconfig](http://editorconfig.org/) configuration that works for the majority of our projects.  Also create:

- [x] Recommended when and how to incorporate the standard editorconfig into your repo
- [x] README for the process of proposing changes (comparable to other standard guides)

cc @redoPop

**Comment by VinSpee** [comment]
see roadrunner's: https://github.com/tedconf/roadrunner/blob/master/.editorconfig

**Comment by redoPop** [comment]
[That .diff rule in ember-cli looks like a good addition.](https://github.com/ember-cli/ember-cli/commit/ff373f85fa2898e428aaa0edee959036dfdfa395)

The only other difference I spotted between its rules and Roadrunner's is that ember-cli doesn't auto-insert final newlines in Handlebars files. [There doesn't seem to be much explanation for that,](https://github.com/ember-cli/ember-cli/commit/4d712210c2f992de07b1eb411d97d576adfb0c9f) and I find final newlines handy in vi/vim. @brenna: any idea what might've prompted that rule?

**Comment by alexdean** [comment]
@vince why does roadrunner require tabs in erb templates?

**Comment by VinSpee** [comment]
honestly no idea.

**Comment by VinSpee** [comment]
@alexdean because @redoPop said so? https://github.com/tedconf/roadrunner/commit/68789f40414e22a07c338b31b24146b6b245d257

**Comment by brenna** [comment]
@redoPop looks like a new line at end of file will cause an unwanted text node to render https://github.com/ember-cli/ember-cli/issues/3738

**Comment by redoPop** [comment]
> why does roadrunner require tabs in erb templates?

[It applies to .html.erb files only.](https://github.com/tedconf/roadrunner/blob/68789f40414e22a07c338b31b24146b6b245d257/.editorconfig#L20) Reasoning was that these templates are responsible for HTML output without any further whitespace control and Roadrunner's HTML is written in a style that is relatively whitespace-heavy [(example)](https://github.com/tedconf/roadrunner/blob/a3d1af315f4310dc9dd1b34e6346a365d02b2393/frontend/components/ribbon/_index.html.erb) so indenting with tabs halves the number of extraneous whitespace characters in HTML output. With a tool like EditorConfig managing indentation styles, it seemed a small but easy win.

Arguments against: the rule creates an inconsistent indentation style, gains are trifling, tabs lower our pay, U+0009 was a mistake, your face is a tab stop, etc.

Happy to remove that rule. Any opposed?

**Comment by redoPop** [comment]
…ah, the sweet silence of consensus!

I've opened PR #58 with a draft `.editorconfig` file and am closing this issue to move discussion that-a-way.

Not sure who to tag for review, so please ping me if you're interested – or just leave comments/thumbs!
