### ISSUE TITLE
distribute rubocop styles as a gem

### ISSUE THREAD

**Issue by alexdean** [tedconf/code-style-guides#70]
right now all our projects fetch our shared rubocop guide directly via HTTP. see [our rubocop README](https://github.com/tedconf/code-style-guides/blob/master/linters/rubocop/README.md#usage) for more details.

## pros to our current approach

new style rules are applied to all projects immediately. no update has to happen in each project to get the latest rules.

## cons for our current approach

rubocop changes a lot. "existing cops getting renamed" is especially problematic. 

for example, if i update a project to use the latest rubocop (0.72.0 as of 2019-07-03), i get the following error

```
   Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-tedconf-code-style-guides-master-linters-rubocop-rubocop-yml, please update it)
```

in order to make our shared guide work, i need to stick to a rubocop release which is prior to this rename. (or i could rename the cop in our style guide, but that breaks everybody who has an old version - with no warning/explanation.)

## proposal

  1. package our shared style guide as a gem like `ted-rubocop-styles`
  1. make that gem depend on a compatible rubocop version
  1. have projects depend on `ted-rubocop-styles` rather than on `rubocop` directly

this does mean all our projects need to update whenever we release a new version of our gem. i don't love that, but i don't see a cleaner way to solve the errors which come with cop renaming.

definitely open to other suggestions.

@tedconf/backenders thumbs up/down on this one?

**Comment by jhirbour** [comment]
This sounds good to me, it would also give the ability to report easier on who's following what version of rubocop rules. 

We should probably resolve https://github.com/tedconf/code-style-guides/pull/69 before we cut a v0.0.1 of the gem.

**Comment by mtwentyman** [comment]
A gem paired with [inherit_gem](https://github.com/rubocop-hq/rubocop/blob/64f6ca77af6aa14dc754f9cc5a8fbf32d4fa4f74/manual/configuration.md#inheriting-configuration-from-a-dependency-gem) and maybe [inherit_mode](https://github.com/rubocop-hq/rubocop/blob/64f6ca77af6aa14dc754f9cc5a8fbf32d4fa4f74/manual/configuration.md#merging-arrays-using-inherit_mode) sounds like a neat idea.

**Comment by alexdean** [comment]
i will add this is not the first time a cop rename has bitten us. see #55.

**Comment by alexdean** [comment]
@tedconf/backenders any objections to moving ahead with this plan?

**Comment by mtwentyman** [comment]
None here

**Comment by alexdean** [comment]
i take silence as consent on this one. just pending time to implement now. i plan to keep the style guide in the same place, so folks can opt-in to the new process as time allows.

if somebody else wants to take a stab at this before i get to it, feel free. please just ping me so we don't duplicate efforts.

**Comment by jhirbour** [comment]
![](https://media.giphy.com/media/3o6ZtpvPW6fqxkE1xu/giphy.gif)

**Comment by mtwentyman** [comment]
Heads up, we've got another one:
```
The `Style/UnneededPercentQ` cop has been renamed to `Style/RedundantPercentQ`
```

**Comment by DanielRussell** [comment]
I tend to prefer dealing with the background noise of frequent updates rather than a big update all at once.  I'd like to use styles-as-a-gem once it's available, but in the meantime I've created a branch `rubocop_latest`.

The objective is `rubocop_latest` is our style guides but functional with the latest released rubocop gem (moving target; anyone who pins their app to `rubocop_latest` should understand that the style guides might change out from under them at any time).

@alexdean I'm game to leave this as an undocumented feature, or to put a note in the tech-guide.
